/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_AndroidMediaPlayer_EchoPrint */

#ifndef _Included_com_example_AndroidMediaPlayer_EchoPrint
#define _Included_com_example_AndroidMediaPlayer_EchoPrint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_AndroidMediaPlayer_EchoPrint
 * Method:    codegen
 * Signature: ([FI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_AndroidMediaPlayer_EchoPrint_codegen
  (JNIEnv *, jobject, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
